<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- scaled down by 0.1 -->
    <!-- Original Values -->
    <!-- Base Lenght - 200 -->
    <!-- Base Width - 150 -->
    <!-- Base Height - 60 -->
    <!-- Wheel Radius - 35 -->
    <!-- Wheel Height - 10 -->

    <xacro:property name="base_length" value="0.94"/>
    <xacro:property name="base_width" value="1.14"/>
    <xacro:property name="base_height" value="0.99"/>
    <xacro:property name="wheel_radius" value="0.23"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="sphere_radius" value="0.075"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="4.0" 
                        l="${base_length}" w="${base_width}" h="${base_height}" 
                        xyz="0 0 0" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix" >
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi /2} 0 0"/>
            <material name="blue" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi /2} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2 * wheel_radius}" h="${2 * wheel_length}"
                                    xyz="0 0 0" rpy="${pi /2} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <link name="caster_wheel">
        <visual>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${sphere_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2 * wheel_radius / 2.0}"
                            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>   
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${base_length/2 - 0.11 - 0.0882} 0 -${base_height/2 + 0.075}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <!-- By changing the Y value, the wheel will be defined for either right or left -->
        <origin xyz="${-(base_length/2)+ 0.15} -${(base_width/2) + 0.05} ${-(base_height/2) + 0.08}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <!-- By changing the Y value, the wheel will be defined for either right or left -->
        <origin xyz="${-(base_length/2)+ 0.15} ${(base_width/2) + 0.05} ${-(base_height/2) + 0.08}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

<!-- ${(base_length / 2) + 0.2441} -->
</robot>